directories:
  output: release
  buildResources: build
appId: com.note.template
productName: Note Template
files:
  - filter:
      - dist/**/*
      - src/electron/**/*
      - package.json
win:
  target: nsis
  icon: public/icon.ico
publish:
  provider: github
  repo: 8x8
  owner: jrzstflr
  releaseType: release
electronVersion: 34.1.1
